# Generated by Django 4.0.5 on 2022-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usercrowd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('profile_img', models.ImageField(upload_to='images/')),
                ('is_active', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
